#!/usr/bin/env bun

import { $, app } from '@gutenye/script.js'

const PUBLISH_PACKAGES = ['common', 'node', 'browser', 'react-native']

// skip models, which is large
app
  .cmd('publish', 'Bump the version and publish packages')
  .add('<version>', 'Version to publish')
  .add('[packages]', `Comma-separated packages (default: ${PUBLISH_PACKAGES.join(',')})`)
  .add(async (version, packages) => {
    await updateVersion('package.json', version)
    for (const pkg of packages?.split(',') ?? PUBLISH_PACKAGES) {
      await updateVersion(`packages/${pkg}/package.json`, version)
      await $`./ake publish`.cwd(`packages/${pkg}`)
    }
  })

app
  .cmd('node example', 'Run the node example')
  .add('[...args]', 'Extra example args')
  .add(async (_args, { argv }) => {
    await $`./ake start ${argv}`.cwd('packages/node/example')
  })

app.cmd('browser example', 'Run the browser example').add(async () => {
  await $`./ake start`.cwd('packages/browser/example')
})

app.cmd('react-native example', 'Run the ReactNative example').add(async () => {
  await $`./ake start`.cwd('packages/react-native/example')
})

app
  .cmd('cpp example', 'Run the cpp example')
  .add('[path]', 'Image path', ['$files'])
  .add(async (path) => {
    const args = path ? [path] : []
    await $`./ake start ${args}`.cwd('packages/react-native/cpp/example')
  })

async function updateVersion(path: string, version: string) {
  const file = Bun.file(path)
  const content = await file.text()
  await Bun.write(file, content.replace(/"version": ".*"/, `"version": "${version}"`))
}

await app.run()
